import { Link, usePage } from "@inertiajs/react";
import { CheckCircle2, Clock3, MessageCircle, ShieldCheck, UsersRound } from "lucide-react";
import divingHero from "@/assets/diving-hero.jpg";
import { BookNowLink } from "@/components/BookNowLink";
import { HeroSection } from "@/components/HeroSection";
import { SecondaryLink } from "@/components/SecondaryButton";
import { SiteLayout } from "@/components/SiteLayout";
import { WHATSAPP_LINK } from "@/data/site";

type Course = { id:number; title:string; description:string; level?:string|null; duration?:string|null; price?:string|null; image_path?:string|null; highlights?:string[]|null };
export default function CourseDetail() { const { course } = usePage<{course:Course}>().props; const image = course.image_path ? `/storage/${course.image_path}` : divingHero; return <SiteLayout><HeroSection compact backgroundImage={image} eyebrow="Diving course" title={course.title} subtitle={course.description} trustLine={`${course.level || "Course level confirmed with you"} • ${course.duration || "Duration on request"} • ${course.price || "Ask for a quote"}`} actions={<><BookNowLink course={course.title} className="px-7 py-3.5">Ask About This Course</BookNowLink><SecondaryLink onDark href={WHATSAPP_LINK} target="_blank" rel="noopener noreferrer" className="px-7 py-3.5"><MessageCircle className="size-4"/>WhatsApp our team</SecondaryLink></>} /><section className="py-14 sm:py-20"><div className="container-page grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><article className="rounded-3xl border border-border bg-card p-6 shadow-sm sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Course overview</p><h2 className="mt-2 text-2xl font-extrabold text-navy">Learn at a Comfortable Pace</h2><p className="mt-4 leading-relaxed text-muted-foreground">{course.description}</p>{course.highlights?.length ? <div className="mt-7 border-t border-border pt-6"><h3 className="font-extrabold text-navy">What this course focuses on</h3><ul className="mt-4 grid gap-3 sm:grid-cols-2">{course.highlights.map(item=><li key={item} className="flex gap-2.5 text-sm leading-relaxed text-foreground"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-primary"/>{item}</li>)}</ul></div> : null}</article><aside className="rounded-3xl bg-surface p-6 sm:p-8"><h2 className="text-xl font-extrabold text-navy">Before you start</h2><ul className="mt-5 space-y-4 text-sm leading-relaxed text-muted-foreground"><li className="flex gap-3"><UsersRound className="size-5 shrink-0 text-primary"/><span>Tell us your previous diving experience and the dates you have available.</span></li><li className="flex gap-3"><ShieldCheck className="size-5 shrink-0 text-primary"/><span>We confirm suitability, medical requirements and the final learning plan before you commit.</span></li><li className="flex gap-3"><Clock3 className="size-5 shrink-0 text-primary"/><span>Duration can be planned around your Zanzibar stay where practical.</span></li></ul><BookNowLink course={course.title} className="mt-7 w-full">Check Availability</BookNowLink></aside></div><div className="container-page mt-8"><Link href="/courses" className="text-sm font-bold text-primary hover:text-coral">← View all courses</Link></div></section></SiteLayout>; }
