import { Link, router, usePage } from "@inertiajs/react";
import { CalendarDays, ChevronLeft, ChevronRight, UsersRound } from "lucide-react";
import { AdminLayout } from "@/components/AdminLayout";

type Status = "new" | "contacted" | "confirmed" | "cancelled" | "completed";
type Booking = { id: number; full_name: string; whatsapp_number: string; guests: number; status: Status; admin_notes?: string | null };
type Slot = { id: number; date: string; start_time?: string | null; capacity?: number | null; spaces_available?: number | null; status: string; guest_note?: string | null; experience: { title: string }; bookings: Booking[] };
type Day = { date: string; slots: Slot[] };

const statusStyle: Record<Status, string> = { new: "bg-sky-500/10 text-sky-700", contacted: "bg-amber-400/15 text-amber-800", confirmed: "bg-emerald-500/10 text-emerald-700", cancelled: "bg-rose-500/10 text-rose-700", completed: "bg-violet-500/10 text-violet-700" };
const formatDay = (date: string) => new Intl.DateTimeFormat("en", { weekday: "short", day: "numeric", month: "short" }).format(new Date(`${date}T12:00:00`));
const shiftWeek = (weekStart: string, amount: number) => { const date = new Date(`${weekStart}T12:00:00`); date.setDate(date.getDate() + amount * 7); return date.toISOString().slice(0, 10); };

export default function BookingCalendar() {
  const { days, weekStart, weekEnd } = usePage<{ days: Day[]; weekStart: string; weekEnd: string }>().props;
  const goToWeek = (date: string) => router.get("/admin/booking-calendar", { week_start: date }, { preserveState: true });
  const totalSlots = days.reduce((total, day) => total + day.slots.length, 0);
  const confirmedGuests = days.flatMap((day) => day.slots).flatMap((slot) => slot.bookings).filter((booking) => booking.status === "confirmed").reduce((total, booking) => total + booking.guests, 0);
  return <AdminLayout title="Booking Calendar">
    <section className="rounded-3xl bg-card p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-accent/25 text-primary"><CalendarDays className="size-6" /></span><div><h2 className="text-xl font-extrabold text-navy">Weekly dive operations</h2><p className="mt-1 text-sm text-muted-foreground">{formatDay(weekStart)} – {formatDay(weekEnd)} · {totalSlots} departure slot{totalSlots === 1 ? "" : "s"} · {confirmedGuests} confirmed guest{confirmedGuests === 1 ? "" : "s"}</p></div></div><div className="flex flex-wrap gap-2"><button onClick={() => goToWeek(shiftWeek(weekStart, -1))} className="inline-flex items-center gap-1 rounded-xl border border-border px-3 py-2 text-sm font-bold text-navy"><ChevronLeft className="size-4" /> Previous</button><button onClick={() => goToWeek(new Date().toISOString().slice(0, 10))} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">This week</button><button onClick={() => goToWeek(shiftWeek(weekStart, 1))} className="inline-flex items-center gap-1 rounded-xl border border-border px-3 py-2 text-sm font-bold text-navy">Next <ChevronRight className="size-4" /></button></div></div></section>
    <div className="mt-7 grid gap-5 xl:grid-cols-7">{days.map((day) => <section key={day.date} className="min-w-0 rounded-3xl border border-border bg-card p-4 shadow-sm"><div className="flex items-center justify-between border-b border-border pb-3"><h2 className="font-extrabold text-navy">{formatDay(day.date)}</h2><span className="rounded-full bg-accent/25 px-2 py-1 text-xs font-bold text-primary">{day.slots.length}</span></div><div className="mt-4 space-y-3">{day.slots.map((slot) => <article key={slot.id} className="rounded-2xl bg-surface p-3"><p className="text-xs font-bold uppercase tracking-wide text-primary">{slot.start_time?.slice(0, 5) || "Time TBC"}</p><h3 className="mt-1 text-sm font-extrabold leading-snug text-navy">{slot.experience.title}</h3><p className="mt-1 text-xs text-muted-foreground">{slot.spaces_available ?? "—"}/{slot.capacity ?? "—"} spaces · {slot.status}</p>{slot.bookings.length ? <div className="mt-3 space-y-2 border-t border-border pt-3">{slot.bookings.map((booking) => <div key={booking.id} className="rounded-xl bg-card p-2"><div className="flex items-start justify-between gap-2"><a href={`https://wa.me/${booking.whatsapp_number.replace(/\D/g, "")}`} target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-navy hover:text-primary">{booking.full_name}</a><span className={`shrink-0 rounded-full px-1.5 py-0.5 text-[10px] font-bold ${statusStyle[booking.status]}`}>{booking.status}</span></div><p className="mt-1 inline-flex items-center gap-1 text-[11px] text-muted-foreground"><UsersRound className="size-3" /> {booking.guests} guest{booking.guests === 1 ? "" : "s"}</p></div>)}</div> : <p className="mt-3 border-t border-border pt-3 text-xs text-muted-foreground">No requests yet</p>}<Link href="/admin" className="mt-3 inline-flex text-xs font-bold text-primary hover:text-coral">Manage inbox →</Link></article>)}{!day.slots.length ? <p className="py-4 text-center text-xs text-muted-foreground">No departures</p> : null}</div></section>)}</div>
  </AdminLayout>;
}
