import { Head, Link, router, usePage } from "@inertiajs/react";
import { CalendarPlus, CreditCard, Download, FilePenLine, Mail, MessageSquare, PlusCircle, Search, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { AdminLayout } from "@/components/AdminLayout";

type Status = "new" | "contacted" | "confirmed" | "cancelled" | "completed";
type PaymentStatus = "not_requested" | "pending" | "partially_paid" | "paid" | "refunded" | "not_required";
type Booking = { id: number; full_name: string; whatsapp_number: string; guest_email?: string | null; preferred_date: string; arrival_date?: string | null; departure_date?: string | null; accommodation?: string | null; guest_request?: string | null; guests: number; experience: string; status?: Status; payment_status?: PaymentStatus; deposit_amount?: string | null; payment_reference?: string | null; payment_notes?: string | null; admin_notes?: string | null; created_at?: string; slot?: { date: string; start_time?: string | null; guest_note?: string | null } | null };
type PaymentSettings = { payment_currency?: string; payment_instructions?: string; payment_terms?: string; google_review_url?: string };
type PaginatedBookings = { data: Booking[]; links: { url: string | null; label: string; active: boolean }[]; from?: number | null; to?: number | null; total: number };
type Filters = { status: string; date: string; search: string };

const statuses: Status[] = ["new", "contacted", "confirmed", "cancelled", "completed"];
const statusStyle: Record<Status, string> = { new: "bg-sky-500/10 text-sky-700", contacted: "bg-amber-400/15 text-amber-800", confirmed: "bg-emerald-500/10 text-emerald-700", cancelled: "bg-rose-500/10 text-rose-700", completed: "bg-violet-500/10 text-violet-700" };
const paymentStatuses: PaymentStatus[] = ["not_requested", "pending", "partially_paid", "paid", "refunded", "not_required"];
const humanStatus = (status: Status) => status.charAt(0).toUpperCase() + status.slice(1);
const humanPaymentStatus = (status: PaymentStatus) => status.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const paymentStyle: Record<PaymentStatus, string> = { not_requested: "bg-slate-500/10 text-slate-700", pending: "bg-amber-400/15 text-amber-800", partially_paid: "bg-sky-500/10 text-sky-700", paid: "bg-emerald-500/10 text-emerald-700", refunded: "bg-rose-500/10 text-rose-700", not_required: "bg-slate-500/10 text-slate-700" };

function whatsappTemplate(booking: Booking, status: Status) {
  const time = booking.slot?.start_time ? ` at ${booking.slot.start_time.slice(0, 5)}` : "";
  const date = booking.slot?.date || booking.preferred_date;
  if (status === "confirmed") return `Hello ${booking.full_name}! Your ${booking.experience} request is confirmed for ${date}${time} for ${booking.guests} guest(s). Please bring swimwear, a towel and any relevant diving certification. We will send any final planning details before your dive. — Easy Blue Divers Zanzibar`;
  if (status === "contacted") return `Hello ${booking.full_name}! Thank you for your ${booking.experience} request for ${date}. We are checking the final availability and will update you shortly. — Easy Blue Divers Zanzibar`;
  if (status === "cancelled") return `Hello ${booking.full_name}. Your ${booking.experience} request for ${date} is no longer available. Please send us alternative dates and we will help you find the best option. — Easy Blue Divers Zanzibar`;
  return `Hello ${booking.full_name}! We received your ${booking.experience} request for ${date}. Our team will check availability and contact you shortly. — Easy Blue Divers Zanzibar`;
}

function BookingCard({ booking, paymentSettings }: { booking: Booking; paymentSettings?: PaymentSettings | null }) {
  const [status, setStatus] = useState<Status>(booking.status || "new");
  const [notes, setNotes] = useState(booking.admin_notes || "");
  const [paymentStatus, setPaymentStatus] = useState<PaymentStatus>(booking.payment_status || "not_requested");
  const [depositAmount, setDepositAmount] = useState(booking.deposit_amount || "");
  const [paymentReference, setPaymentReference] = useState(booking.payment_reference || "");
  const [paymentNotes, setPaymentNotes] = useState(booking.payment_notes || "");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const save = (overrides: Partial<{ status: Status; paymentStatus: PaymentStatus }> = {}) => {
    setError("");
    setSaving(true);
    router.put(`/admin/bookings/${booking.id}`, { status: overrides.status || status, admin_notes: notes, payment_status: overrides.paymentStatus || paymentStatus, deposit_amount: depositAmount || null, payment_reference: paymentReference || null, payment_notes: paymentNotes || null }, { preserveScroll: true, onError: (errors) => setError(errors.status || errors.payment_status || "Could not update this booking."), onFinish: () => setSaving(false) });
  };
  const whatsappUrl = `https://wa.me/${booking.whatsapp_number.replace(/\D/g, "")}?text=${encodeURIComponent(whatsappTemplate(booking, status))}`;
  const paymentMessage = `Hello ${booking.full_name}! To secure your ${booking.experience} booking for ${booking.slot?.date || booking.preferred_date}, please send a deposit${depositAmount ? ` of ${paymentSettings?.payment_currency || "TZS"} ${depositAmount}` : ""}.\n\n${paymentSettings?.payment_instructions || "Please contact us for payment instructions."}${paymentSettings?.payment_terms ? `\n\n${paymentSettings.payment_terms}` : ""}\n\nAfter payment, please send your receipt or reference. Thank you — Easy Blue Divers Zanzibar`;
  const paymentWhatsappUrl = `https://wa.me/${booking.whatsapp_number.replace(/\D/g, "")}?text=${encodeURIComponent(paymentMessage)}`;
  const reviewMessage = `Hello ${booking.full_name}! Thank you for diving with Easy Blue Divers Zanzibar. We hope you enjoyed your ${booking.experience} experience. If you have a minute, your Google review would mean a lot to our small team: ${paymentSettings?.google_review_url || ""}\n\nThank you again!`;
  const reviewWhatsappUrl = `https://wa.me/${booking.whatsapp_number.replace(/\D/g, "")}?text=${encodeURIComponent(reviewMessage)}`;
  return <article className="rounded-3xl border border-border bg-card p-5 shadow-sm transition-shadow hover:shadow-md">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
      <div>
        <div className="flex flex-wrap items-center gap-2"><h2 className="font-extrabold text-navy">{booking.full_name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${statusStyle[status]}`}>{humanStatus(status)}</span><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold ${paymentStyle[paymentStatus]}`}><CreditCard className="size-3" aria-hidden="true" />{humanPaymentStatus(paymentStatus)}</span></div>
        <p className="mt-2 text-sm text-muted-foreground">{booking.experience} · {booking.preferred_date} · {booking.guests} guest{booking.guests === 1 ? "" : "s"}</p>
        {booking.slot ? <p className="mt-1 text-xs font-semibold text-primary">Departure: {booking.slot.date}{booking.slot.start_time ? ` · ${booking.slot.start_time.slice(0, 5)}` : ""}</p> : null}
        <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1"><a href={`https://wa.me/${booking.whatsapp_number.replace(/\D/g, "")}`} target="_blank" rel="noopener noreferrer" className="inline-flex text-sm font-bold text-primary hover:text-coral">WhatsApp: {booking.whatsapp_number}</a>{booking.guest_email ? <a href={`mailto:${booking.guest_email}`} className="inline-flex items-center gap-1 text-sm font-semibold text-muted-foreground hover:text-primary"><Mail className="size-3.5" aria-hidden="true" />{booking.guest_email}</a> : null}</div>
        {booking.arrival_date || booking.departure_date || booking.accommodation || booking.guest_request ? <div className="mt-4 rounded-2xl bg-surface p-3 text-xs leading-relaxed text-muted-foreground"><p className="font-bold uppercase tracking-wide text-navy">Travel details</p><div className="mt-2 grid gap-1 sm:grid-cols-2">{booking.arrival_date ? <p><span className="font-semibold text-navy">Arrival:</span> {booking.arrival_date}</p> : null}{booking.departure_date ? <p><span className="font-semibold text-navy">Departure:</span> {booking.departure_date}</p> : null}{booking.accommodation ? <p className="sm:col-span-2"><span className="font-semibold text-navy">Accommodation:</span> {booking.accommodation}</p> : null}{booking.guest_request ? <p className="sm:col-span-2"><span className="font-semibold text-navy">Guest request:</span> {booking.guest_request}</p> : null}</div></div> : null}
      </div>
      <label className="text-sm font-bold text-navy">Booking status<select value={status} onChange={(event) => setStatus(event.target.value as Status)} className="mt-2 block w-full rounded-xl border border-input bg-background px-3 py-2 text-sm font-semibold text-navy">{statuses.map((item) => <option key={item} value={item}>{humanStatus(item)}</option>)}</select></label>
    </div>
    <details className="group mt-4 rounded-2xl border border-border bg-surface p-4"><summary className="cursor-pointer list-none text-sm font-bold text-navy marker:hidden">Manage booking <span className="ml-1 font-normal text-muted-foreground">— notes, payment and follow-up</span></summary><div className="mt-5">
    <label className="block text-sm font-bold text-navy">Admin notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Internal note, confirmation details or follow-up." className="mt-2 min-h-20 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm font-normal text-foreground" /></label>
    <div className="mt-5 rounded-2xl border border-border bg-surface p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-extrabold text-navy">Deposit & payment</h3><span className="text-xs font-semibold text-muted-foreground">Internal tracking</span></div><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="text-sm font-bold text-navy">Payment status<select value={paymentStatus} onChange={(event) => setPaymentStatus(event.target.value as PaymentStatus)} className="mt-2 block w-full rounded-xl border border-input bg-background px-3 py-2 text-sm font-semibold text-navy">{paymentStatuses.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label><label className="text-sm font-bold text-navy">Deposit amount<input type="number" min="0" step="0.01" value={depositAmount} onChange={(event) => setDepositAmount(event.target.value)} placeholder="Amount / currency" className="mt-2 block w-full rounded-xl border border-input bg-background px-3 py-2 text-sm font-normal text-foreground" /></label><label className="text-sm font-bold text-navy">Payment reference<input value={paymentReference} onChange={(event) => setPaymentReference(event.target.value)} placeholder="Transfer / receipt reference" className="mt-2 block w-full rounded-xl border border-input bg-background px-3 py-2 text-sm font-normal text-foreground" /></label></div><label className="mt-4 block text-sm font-bold text-navy">Payment note<textarea value={paymentNotes} onChange={(event) => setPaymentNotes(event.target.value)} placeholder="Deposit instructions, payment verification or refund note." className="mt-2 min-h-16 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm font-normal text-foreground" /></label></div>
    {error ? <p className="mt-3 rounded-xl bg-destructive/10 p-3 text-sm font-semibold text-destructive">{error}</p> : null}
    <div className="mt-4 flex flex-col gap-3 sm:flex-row"><button type="button" disabled={saving} onClick={() => save()} className="rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground disabled:cursor-wait disabled:opacity-60">{saving ? "Saving…" : "Save booking"}</button><button type="button" disabled={saving} onClick={() => { window.open(`https://wa.me/${booking.whatsapp_number.replace(/\D/g, "")}?text=${encodeURIComponent(whatsappTemplate(booking, "confirmed"))}`, "_blank", "noopener,noreferrer"); save({ status: "confirmed" }); }} className="inline-flex items-center justify-center rounded-full border border-primary/30 px-5 py-2.5 text-sm font-bold text-primary hover:bg-accent/20">Confirm & WhatsApp</button><button type="button" disabled={saving} onClick={() => { window.open(paymentWhatsappUrl, "_blank", "noopener,noreferrer"); save({ paymentStatus: "pending" }); }} className="inline-flex items-center justify-center rounded-full border border-coral/30 px-5 py-2.5 text-sm font-bold text-coral hover:bg-coral/10">Deposit request & WhatsApp</button>{status === "completed" && paymentSettings?.google_review_url ? <a href={reviewWhatsappUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center rounded-full border border-emerald-500/30 px-5 py-2.5 text-sm font-bold text-emerald-700 hover:bg-emerald-500/10">Request Google review</a> : null}</div></div></details>
  </article>;
}

export default function Dashboard() {
  const { bookings, totalBookings, bookingStatusCounts, paymentStatusCounts, filters, siteSettings, readiness } = usePage<{ bookings: PaginatedBookings; totalBookings: number; bookingStatusCounts: Partial<Record<Status, number>>; paymentStatusCounts: Partial<Record<PaymentStatus, number>>; filters: Filters; siteSettings?: PaymentSettings | null; readiness: { settings: boolean; experiences: number; slots: number; courses: number; prices: number; faqs: number } }>().props;
  const [search, setSearch] = useState(filters.search);
  const [status, setStatus] = useState(filters.status);
  const [date, setDate] = useState(filters.date);
  const applyFilters = () => router.get("/admin", { search: search || undefined, status: status || undefined, date: date || undefined }, { preserveState: true, replace: true });
  const clearFilters = () => { setSearch(""); setStatus(""); setDate(""); router.get("/admin", {}, { preserveState: true, replace: true }); };
  const exportParams = new URLSearchParams();
  if (search) exportParams.set("search", search);
  if (status) exportParams.set("status", status);
  if (date) exportParams.set("date", date);
  const exportUrl = `/admin/bookings/export${exportParams.size ? `?${exportParams.toString()}` : ""}`;
  const newBookings = bookingStatusCounts.new || 0;
  const depositsToFollowUp = (paymentStatusCounts.pending || 0) + (paymentStatusCounts.partially_paid || 0);
  return <><Head title="Admin Dashboard" /><AdminLayout title="Booking Dashboard">
    <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-5"><div className="rounded-3xl bg-primary p-6 text-primary-foreground"><p className="text-sm font-semibold">Total booking requests</p><p className="mt-2 text-4xl font-extrabold">{totalBookings}</p></div><div className="rounded-3xl bg-navy p-6 text-navy-foreground"><p className="text-sm font-semibold text-navy-foreground/75">New requests to review</p><p className="mt-2 text-4xl font-extrabold text-turquoise">{newBookings}</p></div><div className="rounded-3xl bg-card p-6 shadow-sm"><p className="text-sm font-semibold text-muted-foreground">Confirmed</p><p className="mt-2 text-4xl font-extrabold text-emerald-600">{bookingStatusCounts.confirmed || 0}</p></div><div className="rounded-3xl bg-card p-6 shadow-sm"><p className="text-sm font-semibold text-muted-foreground">Deposit follow-up</p><p className="mt-2 text-4xl font-extrabold text-amber-600">{depositsToFollowUp}</p></div><div className="rounded-3xl bg-card p-6 shadow-sm"><p className="text-sm font-semibold text-muted-foreground">Completed</p><p className="mt-2 text-4xl font-extrabold text-violet-600">{bookingStatusCounts.completed || 0}</p></div></div>
    <section className="mt-8"><h2 className="text-lg font-extrabold text-navy">Quick actions</h2><p className="mt-1 text-sm text-muted-foreground">The common tasks for running Easy Blue day to day.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Review new bookings", "/admin?status=new", MessageSquare, `${newBookings} new`],["Publish availability", "/admin/dive-planner", CalendarPlus, "Weekly planner"],["Add an experience", "/admin/experiences", PlusCircle, "Diving content"],["Edit website copy", "/admin/content", FilePenLine, "Homepage & pages"]].map(([label, href, Icon, helper]) => <Link key={String(label)} href={String(href)} className="group rounded-3xl border border-border bg-card p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-md"><Icon className="size-5 text-primary" aria-hidden="true" /><p className="mt-4 font-extrabold text-navy">{label}</p><p className="mt-1 text-xs text-muted-foreground">{helper}</p></Link>)}</div></section>
    <section className="mt-8 rounded-3xl border border-border bg-card p-5 shadow-sm"><h2 className="text-lg font-extrabold text-navy">Site readiness</h2><p className="mt-1 text-sm text-muted-foreground">Complete these items before promoting the website.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[["Site settings", readiness.settings, "/admin/settings"],["Published experiences", readiness.experiences > 0, "/admin/experiences"],["Upcoming departure slots", readiness.slots > 0, "/admin/experience-slots"],["Published courses", readiness.courses > 0, "/admin/courses"],["Published prices", readiness.prices > 0, "/admin/prices"],["Published FAQs", readiness.faqs > 0, "/admin/faqs"]].map(([label, complete, href]) => <Link key={String(label)} href={String(href)} className="flex items-center justify-between rounded-2xl bg-surface px-4 py-3 text-sm font-bold text-navy hover:bg-accent/20"><span>{label}</span><span className={complete ? "text-emerald-600" : "text-amber-600"}>{complete ? "Ready" : "Needs setup"}</span></Link>)}</div></section><section className="mt-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-extrabold text-navy">Booking inbox</h2><p className="mt-1 text-sm text-muted-foreground">Search, follow up and confirm every enquiry from one place.</p></div><div className="flex items-center gap-3">{bookings.total ? <p className="text-sm font-semibold text-muted-foreground">Showing {bookings.from || 0}–{bookings.to || 0} of {bookings.total}</p> : null}<a href={exportUrl} className="inline-flex items-center gap-2 rounded-xl border border-primary/30 px-4 py-2.5 text-sm font-bold text-primary hover:bg-accent/20"><Download className="size-4" /> Export CSV</a></div></div>
      <form onSubmit={(event) => { event.preventDefault(); applyFilters(); }} className="mt-5 grid gap-3 rounded-3xl border border-border bg-card p-4 md:grid-cols-[1fr_180px_170px_auto_auto]">
        <label className="relative"><span className="sr-only">Search bookings</span><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, WhatsApp or experience" className="w-full rounded-xl border border-input bg-background py-2.5 pl-10 pr-3 text-sm" /></label>
        <select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{humanStatus(item)}</option>)}</select>
        <input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm" />
        <button className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground"><SlidersHorizontal className="size-4" /> Filter</button><button type="button" onClick={clearFilters} className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold text-navy">Clear</button>
      </form>
      <div className="mt-5 space-y-4">{bookings.data.map((booking) => <BookingCard key={booking.id} booking={booking} paymentSettings={siteSettings} />)}{!bookings.data.length ? <p className="rounded-3xl bg-card p-8 text-center text-muted-foreground">No booking requests match these filters.</p> : null}</div>
      {bookings.links.length > 3 ? <nav className="mt-6 flex flex-wrap gap-2" aria-label="Booking pages">{bookings.links.map((link) => <Link key={link.label} href={link.url || "#"} preserveScroll className={`rounded-lg px-3 py-2 text-sm font-bold ${link.active ? "bg-primary text-primary-foreground" : link.url ? "border border-border text-navy hover:bg-accent/20" : "cursor-not-allowed border border-border text-muted-foreground/50"}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</nav> : null}
    </section>
  </AdminLayout></>;
}
