import { router, useForm, usePage } from "@inertiajs/react";
import { FolderTree, Pencil, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import { AdminLayout } from "@/components/AdminLayout";

type Category = { id: number; name: string; description?: string; sort_order: number };
const field = "mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20";

function CategoryEditor({ item }: { item: Category }) {
  const [editing, setEditing] = useState(false);
  const form = useForm({ name: item.name, description: item.description || "", sort_order: String(item.sort_order) });
  if (!editing) return <article className="flex items-start justify-between gap-4 rounded-2xl bg-card p-5 shadow-sm"><div><h3 className="font-bold text-navy">{item.name}</h3><p className="mt-1 text-sm text-muted-foreground">{item.description || "No description"}</p><p className="mt-2 text-xs font-semibold text-muted-foreground">Display order: {item.sort_order}</p></div><div className="flex shrink-0 gap-1"><button type="button" onClick={() => setEditing(true)} className="rounded-full p-2 text-primary hover:bg-primary/10" aria-label={`Edit ${item.name}`}><Pencil className="size-4" /></button><button type="button" onClick={() => window.confirm(`Delete ${item.name}?`) && router.delete(`/admin/experience-categories/${item.id}`)} className="rounded-full p-2 text-destructive hover:bg-destructive/10" aria-label={`Delete ${item.name}`}><Trash2 className="size-4" /></button></div></article>;
  return <article className="rounded-3xl border border-primary/30 bg-card p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><h3 className="font-extrabold text-navy">Edit {item.name}</h3><button type="button" onClick={() => setEditing(false)} className="text-sm font-bold text-muted-foreground">Close</button></div><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); form.put(`/admin/experience-categories/${item.id}`, { onSuccess: () => setEditing(false) }); }}><label className="text-sm font-bold text-navy">Category name<input required value={form.data.name} onChange={(event) => form.setData("name", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Display order<input type="number" min="0" value={form.data.sort_order} onChange={(event) => form.setData("sort_order", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy md:col-span-2">Short description<textarea value={form.data.description} onChange={(event) => form.setData("description", event.target.value)} className={`${field} min-h-24`} /></label><div className="flex gap-3 md:col-span-2"><button disabled={form.processing} className="rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60">{form.processing ? "Saving…" : "Save changes"}</button><button type="button" onClick={() => setEditing(false)} className="rounded-full border border-border px-5 py-2.5 text-sm font-bold text-navy">Cancel</button></div></form></article>;
}

export default function ExperienceCategories() {
  const { items } = usePage<{ items: Category[] }>().props;
  const [adding, setAdding] = useState(false);
  const form = useForm({ name: "", description: "", sort_order: "0" });
  const closeAdd = () => { setAdding(false); form.reset(); };
  return <AdminLayout title="Experience Categories"><section className="rounded-3xl bg-card p-6 shadow-sm lg:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-accent/25 text-primary"><FolderTree className="size-5" /></span><div><h2 className="text-lg font-extrabold text-navy">Organise your experiences</h2><p className="mt-1 text-sm text-muted-foreground">Examples: Beginner Diving, Certified Diving, Private Diving and Snorkelling.</p></div></div><button type="button" onClick={() => setAdding(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground"><Plus className="size-4" />Add category</button></div>{adding ? <form className="mt-7 border-t border-border pt-6" onSubmit={(event) => { event.preventDefault(); form.post("/admin/experience-categories", { onSuccess: closeAdd }); }}><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-navy">Category name<input required value={form.data.name} onChange={(event) => form.setData("name", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Display order<input type="number" min="0" value={form.data.sort_order} onChange={(event) => form.setData("sort_order", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy md:col-span-2">Short description<textarea value={form.data.description} onChange={(event) => form.setData("description", event.target.value)} className={`${field} min-h-24`} /></label></div><div className="mt-5 flex flex-wrap gap-3"><button disabled={form.processing} className="rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground disabled:opacity-60">{form.processing ? "Saving…" : "Save category"}</button><button type="button" onClick={closeAdd} className="inline-flex items-center gap-2 rounded-full border border-border px-5 py-3 text-sm font-bold text-navy"><X className="size-4" />Cancel</button></div></form> : null}</section><section className="mt-8"><h2 className="text-xl font-extrabold text-navy">Current categories</h2><p className="mt-1 text-sm text-muted-foreground">Use the pencil icon to change a category that already exists.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{items.map((item) => <CategoryEditor key={item.id} item={item} />)}{!items.length ? <p className="rounded-2xl bg-card p-6 text-sm text-muted-foreground">No categories yet.</p> : null}</div></section></AdminLayout>;
}
