import { router, useForm, usePage } from "@inertiajs/react";
import { Pencil, Trash2 } from "lucide-react";
import { useState } from "react";
import { AdminLayout } from "@/components/AdminLayout";
import { AdminAddPanel } from "@/components/AdminAddPanel";

type Faq = { id: number; question: string; answer: string; sort_order: number; is_active: boolean };
type FaqData = { question: string; answer: string; sort_order: number; is_active: boolean };
const field = "mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm text-navy outline-none focus:border-primary focus:ring-2 focus:ring-primary/15";

function FaqEditor({ item }: { item: Faq }) {
  const [editing, setEditing] = useState(false);
  const form = useForm<FaqData>({ question: item.question, answer: item.answer, sort_order: item.sort_order, is_active: item.is_active });
  if (!editing) return <article className="flex flex-col gap-4 rounded-3xl bg-card p-5 shadow-sm sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-extrabold text-navy">{item.question}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.is_active ? "bg-emerald-500/10 text-emerald-700" : "bg-slate-500/10 text-slate-700"}`}>{item.is_active ? "Published" : "Draft"}</span></div><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">{item.answer}</p><p className="mt-2 text-xs text-muted-foreground">Display order {item.sort_order}</p></div><div className="flex shrink-0 gap-2"><button type="button" onClick={() => setEditing(true)} className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><Pencil className="size-3.5" />Edit</button><button type="button" onClick={() => { if (window.confirm(`Delete “${item.question}”? This cannot be undone.`)) router.delete(`/admin/faqs/${item.id}`); }} className="rounded-full p-2 text-destructive hover:bg-destructive/10" aria-label="Delete FAQ"><Trash2 className="size-4" /></button></div></article>;
  return <article className="rounded-3xl border border-primary/30 bg-card p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-extrabold text-navy">Edit FAQ</h2><button type="button" onClick={() => setEditing(false)} className="text-sm font-bold text-muted-foreground">Close</button></div><form className="mt-5 grid gap-4" onSubmit={(event) => { event.preventDefault(); form.put(`/admin/faqs/${item.id}`, { onSuccess: () => setEditing(false) }); }}><label className="text-sm font-bold text-navy">Question<input required value={form.data.question} onChange={(event) => form.setData("question", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Answer<textarea required value={form.data.answer} onChange={(event) => form.setData("answer", event.target.value)} className={`${field} min-h-28`} /></label><div className="flex flex-wrap items-end gap-5"><label className="w-40 text-sm font-bold text-navy">Display order<input type="number" min="0" value={form.data.sort_order} onChange={(event) => form.setData("sort_order", Number(event.target.value))} className={field} /></label><label className="mb-3 inline-flex items-center gap-2 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData("is_active", event.target.checked)} className="size-4 accent-primary" />Publish on website</label></div><div className="flex gap-3"><button disabled={form.processing} className="rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground disabled:opacity-60">{form.processing ? "Saving…" : "Save changes"}</button><button type="button" onClick={() => setEditing(false)} className="rounded-full border border-border px-6 py-3 text-sm font-bold text-navy">Cancel</button></div></form></article>;
}

export default function Faqs() {
  const { items } = usePage<{ items: Faq[] }>().props;
  const form = useForm<FaqData>({ question: "", answer: "", sort_order: 0, is_active: true });
  return <AdminLayout title="FAQs"><AdminAddPanel title="Add frequently asked question" description="Published questions appear across public booking and course pages."><form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); form.post("/admin/faqs", { onSuccess: () => form.reset() }); }}><label className="text-sm font-bold text-navy">Question<input required value={form.data.question} onChange={(event) => form.setData("question", event.target.value)} placeholder="e.g. Is equipment included?" className={field} /></label><label className="text-sm font-bold text-navy">Answer<textarea required value={form.data.answer} onChange={(event) => form.setData("answer", event.target.value)} placeholder="Give a short, clear answer that helps a guest decide." className={`${field} min-h-28`} /></label><div className="flex flex-wrap items-end gap-5"><label className="w-40 text-sm font-bold text-navy">Display order<input type="number" min="0" value={form.data.sort_order} onChange={(event) => form.setData("sort_order", Number(event.target.value))} className={field} /></label><label className="mb-3 inline-flex items-center gap-2 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData("is_active", event.target.checked)} className="size-4 accent-primary" />Publish immediately</label></div><button disabled={form.processing} className="w-fit rounded-full bg-primary px-6 py-3 font-bold text-primary-foreground disabled:opacity-60">{form.processing ? "Saving…" : "Add FAQ"}</button></form></AdminAddPanel><section className="mt-8 space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-xl font-extrabold text-navy">Manage FAQs</h2><p className="mt-1 text-sm text-muted-foreground">Edit the answer, order or visibility any time.</p></div><span className="text-sm font-bold text-muted-foreground">{items.length} total</span></div>{items.map((item) => <FaqEditor key={item.id} item={item} />)}{!items.length ? <p className="rounded-2xl bg-card p-6 text-muted-foreground">No FAQs yet.</p> : null}</section></AdminLayout>;
}
