import { router, useForm, usePage } from "@inertiajs/react";
import { Pencil, Sparkles, Trash2 } from "lucide-react";
import { useState } from "react";
import { AdminLayout } from "@/components/AdminLayout";
import { AdminAddPanel } from "@/components/AdminAddPanel";

type Item = { id: number; title: string; description: string; price_from?: string | null; included_items?: string[] | null; sort_order?: number; is_featured: boolean; is_active: boolean };
type PackageData = { title: string; description: string; price_from: string; included_items: string; sort_order: string; is_featured: boolean; is_active: boolean };
const field = "mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20";
const blank: PackageData = { title: "", description: "", price_from: "", included_items: "", sort_order: "0", is_featured: false, is_active: true };
const toLines = (items?: string[] | null) => items?.join("\n") ?? "";

function PackageFields({ form }: { form: ReturnType<typeof useForm<PackageData>> }) {
  return <div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-navy">Package name<input required placeholder="e.g. Guided Fun Dives" value={form.data.title} onChange={(event) => form.setData("title", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Starting price<input placeholder="e.g. From USD 90" value={form.data.price_from} onChange={(event) => form.setData("price_from", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Display order <span className="font-normal text-muted-foreground">(lower appears first)</span><input type="number" min="0" max="9999" value={form.data.sort_order} onChange={(event) => form.setData("sort_order", event.target.value)} className={field} /></label><div className="hidden md:block" /><label className="text-sm font-bold text-navy md:col-span-2">Package description<textarea required placeholder="Describe the package and why it is a good fit." value={form.data.description} onChange={(event) => form.setData("description", event.target.value)} className={`${field} min-h-28`} /></label><label className="text-sm font-bold text-navy md:col-span-2">Included in this package <span className="font-normal text-muted-foreground">(one item per line)</span><textarea placeholder={"Professional dive guide\nTanks and weights\nWater and safety briefing"} value={form.data.included_items} onChange={(event) => form.setData("included_items", event.target.value)} className={`${field} min-h-28`} /></label></div>;
}

function PackageEditor({ item }: { item: Item }) {
  const [editing, setEditing] = useState(false);
  const form = useForm<PackageData>({ title: item.title, description: item.description, price_from: item.price_from ?? "", included_items: toLines(item.included_items), sort_order: String(item.sort_order ?? 0), is_featured: item.is_featured, is_active: item.is_active });
  if (!editing) return <article className="flex flex-col gap-4 rounded-3xl bg-card p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><b className="text-navy">{item.title}</b>{item.is_featured ? <span className="inline-flex items-center gap-1 rounded-full bg-accent/25 px-2.5 py-1 text-xs font-bold text-primary"><Sparkles className="size-3" />Featured</span> : null}</div><p className="mt-1 text-sm text-muted-foreground">{item.price_from || "Price on request"} · Display order {item.sort_order ?? 0}</p><p className={`mt-1 text-xs font-bold ${item.is_active ? "text-emerald-600" : "text-muted-foreground"}`}>{item.is_active ? "Published" : "Draft"}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setEditing(true)} className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><Pencil className="size-3.5" />Edit</button><button type="button" onClick={() => { if (window.confirm(`Delete “${item.title}”? This cannot be undone.`)) router.delete(`/admin/prices/${item.id}`); }} className="rounded-full p-2 text-destructive hover:bg-destructive/10" aria-label={`Delete ${item.title}`}><Trash2 className="size-4" /></button></div></article>;
  return <article className="rounded-3xl border border-primary/30 bg-card p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-extrabold text-navy">Edit: {item.title}</h2><button type="button" onClick={() => setEditing(false)} className="text-sm font-bold text-muted-foreground">Close</button></div><form className="mt-6" onSubmit={(event) => { event.preventDefault(); form.put(`/admin/prices/${item.id}`, { onSuccess: () => setEditing(false) }); }}><PackageFields form={form} /><div className="mt-5 flex flex-wrap gap-5"><label className="inline-flex items-center gap-2 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_featured} onChange={(event) => form.setData("is_featured", event.target.checked)} className="size-4 accent-primary" /> Feature this package</label><label className="inline-flex items-center gap-2 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData("is_active", event.target.checked)} className="size-4 accent-primary" /> Publish this package</label></div><div className="mt-6 flex gap-3"><button disabled={form.processing} className="rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground disabled:opacity-60">{form.processing ? "Saving…" : "Save changes"}</button><button type="button" onClick={() => setEditing(false)} className="rounded-full border border-border px-6 py-3 text-sm font-bold text-navy">Cancel</button></div></form></article>;
}

export default function Prices() {
  const { items } = usePage<{ items: Item[] }>().props;
  const form = useForm<PackageData>(blank);
  return <AdminLayout title="Prices & Packages"><AdminAddPanel title="Add a package" description="Show a clear starting price, the main inclusions and the exact order guests will see."><form onSubmit={(event) => { event.preventDefault(); form.post("/admin/prices", { onSuccess: () => form.reset() }); }}><PackageFields form={form} /><div className="mt-5 flex flex-wrap gap-5"><label className="inline-flex items-center gap-2 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_featured} onChange={(event) => form.setData("is_featured", event.target.checked)} className="size-4 accent-primary" /> Feature this package</label><label className="inline-flex items-center gap-2 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData("is_active", event.target.checked)} className="size-4 accent-primary" /> Publish immediately</label></div><button disabled={form.processing} className="mt-6 rounded-full bg-primary px-6 py-3 font-bold text-primary-foreground disabled:opacity-60">{form.processing ? "Saving…" : "Save package"}</button></form></AdminAddPanel><section className="mt-8 space-y-4"><h2 className="text-xl font-extrabold text-navy">Manage packages</h2>{items.map((item) => <PackageEditor key={item.id} item={item} />)}{!items.length ? <p className="rounded-2xl bg-card p-6 text-sm text-muted-foreground">No packages added yet.</p> : null}</section></AdminLayout>;
}
