import { router, useForm, usePage } from "@inertiajs/react";
import { Pencil, Sparkles, Star, Trash2 } from "lucide-react";
import { useState } from "react";
import { AdminLayout } from "@/components/AdminLayout";
import { AdminAddPanel } from "@/components/AdminAddPanel";

type Review = { id: number; name: string; country?: string | null; rating: number; review: string; is_active: boolean; is_featured: boolean };
const field = "mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm text-navy outline-none focus:border-primary focus:ring-2 focus:ring-primary/15";

function ReviewCard({ item }: { item: Review }) {
  const [editing, setEditing] = useState(false);
  const form = useForm({ name: item.name, country: item.country || "", rating: item.rating, review: item.review, is_active: item.is_active, is_featured: item.is_featured });
  if (!editing) return <article className="flex flex-col gap-4 rounded-3xl border border-border bg-card p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold text-navy">{item.name}{item.country ? ` · ${item.country}` : ""}</p>{item.is_featured ? <span className="inline-flex items-center gap-1 rounded-full bg-accent/25 px-2 py-1 text-[0.65rem] font-bold text-primary"><Sparkles className="size-3" />Featured</span> : null}<span className={`rounded-full px-2 py-1 text-[0.65rem] font-bold ${item.is_active ? "bg-emerald-500/10 text-emerald-700" : "bg-slate-500/10 text-slate-600"}`}>{item.is_active ? "Published" : "Hidden"}</span></div><p className="mt-1 flex gap-0.5 text-coral">{Array.from({ length: item.rating }).map((_, index) => <Star key={index} className="size-4 fill-current" />)}</p><p className="mt-2 line-clamp-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{item.review}</p></div><div className="flex shrink-0 gap-2"><button type="button" onClick={() => setEditing(true)} className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><Pencil className="size-3.5" />Edit</button><button type="button" onClick={() => { if (window.confirm(`Delete review from ${item.name}? This cannot be undone.`)) router.delete(`/admin/reviews/${item.id}`); }} className="rounded-full p-2 text-destructive hover:bg-destructive/10" aria-label={`Delete review from ${item.name}`}><Trash2 className="size-4" /></button></div></article>;
  return <article className="rounded-3xl border border-primary/30 bg-card p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-extrabold text-navy">Edit review: {item.name}</h2><button type="button" onClick={() => setEditing(false)} className="text-sm font-bold text-muted-foreground">Close</button></div><div className="mt-5 grid gap-4"><label className="text-sm font-bold text-navy">Guest name<input value={form.data.name} onChange={(event) => form.setData("name", event.target.value)} className={field} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-navy">Country<input value={form.data.country} onChange={(event) => form.setData("country", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Rating<select value={form.data.rating} onChange={(event) => form.setData("rating", Number(event.target.value))} className={field}>{[5, 4, 3, 2, 1].map((value) => <option key={value} value={value}>{value} stars</option>)}</select></label></div><label className="text-sm font-bold text-navy">Review<textarea value={form.data.review} onChange={(event) => form.setData("review", event.target.value)} className={`${field} min-h-28`} /></label><div className="flex flex-wrap gap-5"><label className="inline-flex cursor-pointer items-center gap-3 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData("is_active", event.target.checked)} className="size-4 rounded border-border text-primary" />Show on public website</label><label className="inline-flex cursor-pointer items-center gap-3 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_featured} onChange={(event) => form.setData("is_featured", event.target.checked)} className="size-4 rounded border-border text-primary" />Show first on Home</label></div></div><div className="mt-5 flex flex-wrap gap-3 border-t border-border pt-5"><button onClick={() => form.put(`/admin/reviews/${item.id}`, { onSuccess: () => setEditing(false) })} disabled={form.processing} className="rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60">Save review</button><button type="button" onClick={() => setEditing(false)} className="rounded-full border border-border px-5 py-2.5 text-sm font-bold text-navy">Cancel</button></div></article>;
}

export default function Reviews() {
  const { items } = usePage<{ items: Review[] }>().props;
  const form = useForm({ name: "", country: "", rating: 5, review: "", is_active: true, is_featured: false });
  return <AdminLayout title="Guest Reviews"><AdminAddPanel title="Add a verified guest review" description="Published reviews appear in the public homepage testimonial section."><form onSubmit={(event) => { event.preventDefault(); form.post("/admin/reviews", { onSuccess: () => form.reset() }); }} className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-navy">Guest name<input required value={form.data.name} onChange={(event) => form.setData("name", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Country<input value={form.data.country} onChange={(event) => form.setData("country", event.target.value)} className={field} /></label><label className="text-sm font-bold text-navy">Rating<select value={form.data.rating} onChange={(event) => form.setData("rating", Number(event.target.value))} className={field}>{[5, 4, 3, 2, 1].map((value) => <option key={value} value={value}>{value} stars</option>)}</select></label><div className="flex flex-col justify-end gap-3 pb-1 text-sm font-bold text-navy"><label className="inline-flex items-center gap-3"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData("is_active", event.target.checked)} className="size-4 rounded border-border text-primary" />Publish immediately</label><label className="inline-flex items-center gap-3"><input type="checkbox" checked={form.data.is_featured} onChange={(event) => form.setData("is_featured", event.target.checked)} className="size-4 rounded border-border text-primary" />Show first on Home</label></div><label className="text-sm font-bold text-navy md:col-span-2">Review<textarea required value={form.data.review} onChange={(event) => form.setData("review", event.target.value)} className={`${field} min-h-28`} /></label><button disabled={form.processing} className="rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground disabled:opacity-60 md:justify-self-start">{form.processing ? "Saving…" : "Add review"}</button></form></AdminAddPanel><section className="mt-8"><div className="flex items-center justify-between"><div><h2 className="text-xl font-extrabold text-navy">Manage reviews</h2><p className="mt-1 text-sm text-muted-foreground">Hide a review without deleting it, or update its details anytime.</p></div><span className="text-sm font-bold text-muted-foreground">{items.length} total</span></div><div className="mt-5 grid gap-5 xl:grid-cols-2">{items.map((item) => <ReviewCard key={item.id} item={item} />)}{!items.length ? <p className="rounded-3xl bg-card p-8 text-center text-muted-foreground xl:col-span-2">No guest reviews yet.</p> : null}</div></section></AdminLayout>;
}
