import { Link, useForm, usePage } from "@inertiajs/react";
import { BookOpen, CalendarDays, CheckCircle2, ExternalLink, FileText, Image, MapPinned, MessageSquare, Pencil, Settings, ShieldCheck, Sparkles, Tag, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { AdminLayout } from "@/components/AdminLayout";

type Block = { key: string; title?: string | null; subtitle?: string | null; body?: string | null; data?: { image_path?: string } | null };
type Section = { key: string; name: string; description: string; href: string; titleLabel: string; subtitleLabel: string; bodyLabel: string; titleHint: string; subtitleHint: string; bodyHint: string; hasImage?: boolean };
type Action = { label: string; href?: string; editKey?: string; add?: boolean };
type PublicPage = { title: string; description: string; href: string; icon: typeof FileText; actions: Action[] };
type DivingOverview = {
  categories: { id: number; name: string; description?: string | null; is_active: boolean }[];
  experiences: { id: number; title: string; duration?: string | null; level?: string | null; price_from?: string | null; is_active: boolean; experience_category?: { name: string } | null }[];
  sites: { id: number; name: string; area?: string | null; level?: string | null; is_active: boolean }[];
  upcomingDays: { id: number; date: string; status: string; spaces_available?: number | null; is_active: boolean }[];
};

const sections: Section[] = [
  { key: "home_hero", name: "Home hero", description: "The first message visitors see on the home page.", href: "/", titleLabel: "Hero heading", subtitleLabel: "Hero subtitle", bodyLabel: "Trust line", titleHint: "Discover Zanzibar Beneath the Surface", subtitleHint: "Safe, professional and unforgettable diving experiences…", bodyHint: "Beginner-friendly • Certified diver options • Jambiani, Zanzibar", hasImage: true },
  { key: "about_story", name: "About Us", description: "Your story and personal promise to guests.", href: "/about", titleLabel: "Page heading", subtitleLabel: "Hero subtitle", bodyLabel: "Story introduction", titleHint: "A Friendly Way to Discover Zanzibar Underwater", subtitleHint: "Professional diving, local reef knowledge and a relaxed welcome…", bodyHint: "We created Easy Blue Divers Zanzibar for people who want…", hasImage: true },
  { key: "contact_intro", name: "Contact Page", description: "Set expectations before a guest sends an enquiry.", href: "/contact", titleLabel: "Page heading", subtitleLabel: "Hero subtitle", bodyLabel: "Contact introduction", titleHint: "Let’s Plan Your Zanzibar Dive", subtitleHint: "Share your travel dates and diving experience…", bodyHint: "For the fastest reply, send your preferred date…", hasImage: true },
  { key: "safety_hero", name: "Safety & Planning", description: "Explain clear planning and guest confidence.", href: "/safety", titleLabel: "Page heading", subtitleLabel: "Hero subtitle", bodyLabel: "Planning introduction", titleHint: "Safety Starts With Clear Planning", subtitleHint: "Understand your experience before you book…", bodyHint: "A good dive day starts with the right information…", hasImage: true },
  { key: "dive_services_hero", name: "Dive Services", description: "Introduce guided dives, private groups and Zanzibar trip planning.", href: "/dive-services", titleLabel: "Page heading", subtitleLabel: "Hero subtitle", bodyLabel: "Introductory message", titleHint: "Dive Your Way in Zanzibar", subtitleHint: "Guided dives, beginner experiences and flexible planning…", bodyHint: "Tell us your dates, experience and interests; we will suggest the right plan.", hasImage: true },
  { key: "booking_terms", name: "Booking Terms", description: "Important booking, weather and safety conditions.", href: "/booking-terms", titleLabel: "Page title", subtitleLabel: "Page introduction", bodyLabel: "Terms content", titleHint: "Booking Terms", subtitleHint: "Clear information before you reserve your Zanzibar dive.", bodyHint: "Write paragraphs here. Separate paragraphs with a blank line." },
  { key: "privacy_policy", name: "Privacy Policy", description: "Explain how guest contact and booking details are used.", href: "/privacy", titleLabel: "Page title", subtitleLabel: "Page introduction", bodyLabel: "Privacy content", titleHint: "Privacy Policy", subtitleHint: "How Easy Blue Divers uses the information you share…", bodyHint: "Write paragraphs here. Separate paragraphs with a blank line." },
];

const publicPages: PublicPage[] = [
  { title: "Home", description: "Hero message, featured diving, availability, reviews and FAQs.", href: "/", icon: Sparkles, actions: [{ label: "Edit hero", editKey: "home_hero" }, { label: "Experiences", href: "/admin/experiences", add: true }, { label: "Reviews", href: "/admin/reviews" }, { label: "FAQs", href: "/admin/faqs", add: true }] },
  { title: "Diving & availability", description: "Service introduction, experience categories, dive sites and the weekly planner.", href: "/dive-services", icon: CalendarDays, actions: [{ label: "Edit intro", editKey: "dive_services_hero" }, { label: "Experiences", href: "/admin/experiences", add: true }, { label: "Dive sites", href: "/admin/dive-sites", add: true }, { label: "Weekly planner", href: "/admin/dive-planner", add: true }] },
  { title: "Courses & prices", description: "Course options and the package prices that guests compare before booking.", href: "/courses", icon: BookOpen, actions: [{ label: "Courses", href: "/admin/courses", add: true }, { label: "Prices", href: "/admin/prices", add: true }] },
  { title: "About & team", description: "Your dive-centre story, team profiles and qualifications that build trust.", href: "/about", icon: Users, actions: [{ label: "Edit About", editKey: "about_story" }, { label: "Team members", href: "/admin/team", add: true }] },
  { title: "Gallery", description: "Real diving, equipment and centre photos displayed for potential guests.", href: "/gallery", icon: Image, actions: [{ label: "Manage gallery", href: "/admin/gallery", add: true }] },
  { title: "Contact & footer", description: "Contact introduction, WhatsApp, email, maps pin, business hours and social links.", href: "/contact", icon: MessageSquare, actions: [{ label: "Edit contact text", editKey: "contact_intro" }, { label: "Contact settings", href: "/admin/settings" }] },
  { title: "Safety & planning", description: "Guest safety explanation plus the planning guidance shown before they book.", href: "/safety", icon: ShieldCheck, actions: [{ label: "Edit safety page", editKey: "safety_hero" }] },
  { title: "Legal pages", description: "Booking terms, weather conditions and privacy information.", href: "/booking-terms", icon: FileText, actions: [{ label: "Booking terms", editKey: "booking_terms" }, { label: "Privacy policy", editKey: "privacy_policy" }] },
];

const field = "mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm text-navy outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15";

export default function SiteContent() {
  const { blocks, diving } = usePage<{ blocks: Block[]; diving: DivingOverview }>().props;
  const [activeKey, setActiveKey] = useState<string | null>(null);
  const active = useMemo(() => sections.find((section) => section.key === activeKey) || null, [activeKey]);
  const form = useForm<{ key: string; title: string; subtitle: string; body: string; image: File | null }>({ key: "", title: "", subtitle: "", body: "", image: null });
  const isCustomized = (key: string) => { const block = blocks.find((item) => item.key === key); return Boolean(block?.title || block?.subtitle || block?.body || block?.data?.image_path); };
  const startEdit = (key: string) => {
    const section = sections.find((item) => item.key === key); if (!section) return;
    const block = blocks.find((item) => item.key === key);
    form.setData({ key, title: block?.title || "", subtitle: block?.subtitle || "", body: block?.body || "", image: null });
    setActiveKey(key);
    window.setTimeout(() => document.getElementById("content-editor")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0);
  };
  const closeEditor = () => { setActiveKey(null); form.reset(); };

  return <AdminLayout title="Website Manager">
    <section className="rounded-3xl bg-navy p-6 text-navy-foreground shadow-sm sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-turquoise/15 text-turquoise"><Sparkles className="size-6" /></span><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-turquoise">Public website map</p><h2 className="mt-2 text-xl font-extrabold sm:text-2xl">Everything your guests see, in one place.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-navy-foreground/75">Choose a page below to edit its words or manage the items shown on it. Each action opens the exact tool you need.</p></div></div><Link href="/" target="_blank" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white/10 px-4 py-3 text-sm font-bold text-white transition hover:bg-white/20"><ExternalLink className="size-4" />View website</Link></div></section>

    <section className="mt-8"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-extrabold text-navy">Public pages</h2><p className="mt-1 text-sm text-muted-foreground">Start here whenever you want to add, edit or check public content.</p></div><p className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-700"><CheckCircle2 className="size-4" />Changes appear after saving</p></div><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{publicPages.map((page) => { const Icon = page.icon; const editableActions = page.actions.filter((action) => action.editKey); const customized = editableActions.some((action) => action.editKey && isCustomized(action.editKey)); return <article key={page.title} className="flex min-h-72 flex-col rounded-3xl border border-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-accent/25 text-primary"><Icon className="size-5" /></span>{editableActions.length ? <span className={`rounded-full px-2.5 py-1 text-[0.68rem] font-bold ${customized ? "bg-emerald-500/10 text-emerald-700" : "bg-surface text-muted-foreground"}`}>{customized ? "Content edited" : "Default copy"}</span> : <span className="rounded-full bg-surface px-2.5 py-1 text-[0.68rem] font-bold text-muted-foreground">Managed list</span>}</div><h3 className="mt-5 text-lg font-extrabold text-navy">{page.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{page.description}</p><div className="mt-auto flex flex-wrap gap-2 border-t border-border pt-5">{page.actions.map((action) => action.editKey ? <button type="button" key={action.label} onClick={() => startEdit(action.editKey!)} className="inline-flex items-center gap-1.5 rounded-xl bg-primary px-3 py-2.5 text-xs font-extrabold text-primary-foreground"><Pencil className="size-3.5" />{action.label}</button> : <Link key={action.label} href={action.href!} className="inline-flex items-center gap-1.5 rounded-xl border border-border px-3 py-2.5 text-xs font-extrabold text-navy transition hover:border-primary/40 hover:text-primary">{action.add ? <span className="text-base leading-none">+</span> : null}{action.label}</Link>)}<Link href={page.href} target="_blank" aria-label={`View ${page.title}`} className="ml-auto inline-flex size-9 items-center justify-center rounded-xl border border-border text-navy hover:border-primary/40 hover:text-primary"><ExternalLink className="size-4" /></Link></div></article>; })}</div></section>

    <section className="mt-10 rounded-3xl border border-primary/20 bg-card p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Diving section</p><h2 className="mt-1 text-xl font-extrabold text-navy">Current diving content</h2><p className="mt-1 text-sm text-muted-foreground">These are the real items currently stored in your website. Open the correct manager to edit an item or add a new one.</p></div><Link href="/dive-services" target="_blank" className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-coral"><ExternalLink className="size-4" />View diving page</Link></div><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-4">
      <article className="rounded-2xl bg-surface p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-extrabold text-navy">Categories</h3><span className="rounded-full bg-card px-2.5 py-1 text-xs font-bold text-primary">{diving.categories.length}</span></div><div className="mt-4 space-y-2">{diving.categories.slice(0, 4).map((item) => <div key={item.id} className="rounded-xl bg-card px-3 py-2"><p className="text-sm font-bold text-navy">{item.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{item.is_active ? "Published" : "Hidden"}</p></div>)}{!diving.categories.length ? <p className="text-sm text-muted-foreground">No categories yet.</p> : null}</div><Link href="/admin/experience-categories" className="mt-4 inline-flex items-center gap-1.5 text-xs font-extrabold text-primary hover:text-coral"><Pencil className="size-3.5" />Manage / add category</Link></article>
      <article className="rounded-2xl bg-surface p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-extrabold text-navy">Experiences</h3><span className="rounded-full bg-card px-2.5 py-1 text-xs font-bold text-primary">{diving.experiences.length}</span></div><div className="mt-4 space-y-2">{diving.experiences.slice(0, 4).map((item) => <div key={item.id} className="rounded-xl bg-card px-3 py-2"><p className="truncate text-sm font-bold text-navy">{item.title}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{item.experience_category?.name || item.level || "No category"} · {item.is_active ? "Published" : "Hidden"}</p></div>)}{!diving.experiences.length ? <p className="text-sm text-muted-foreground">No experiences yet.</p> : null}</div><Link href="/admin/experiences" className="mt-4 inline-flex items-center gap-1.5 text-xs font-extrabold text-primary hover:text-coral"><Pencil className="size-3.5" />Manage / add experience</Link></article>
      <article className="rounded-2xl bg-surface p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-extrabold text-navy">Dive sites</h3><span className="rounded-full bg-card px-2.5 py-1 text-xs font-bold text-primary">{diving.sites.length}</span></div><div className="mt-4 space-y-2">{diving.sites.slice(0, 4).map((item) => <div key={item.id} className="rounded-xl bg-card px-3 py-2"><p className="truncate text-sm font-bold text-navy">{item.name}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{item.area || item.level || "Zanzibar"} · {item.is_active ? "Published" : "Hidden"}</p></div>)}{!diving.sites.length ? <p className="text-sm text-muted-foreground">No dive sites yet.</p> : null}</div><Link href="/admin/dive-sites" className="mt-4 inline-flex items-center gap-1.5 text-xs font-extrabold text-primary hover:text-coral"><Pencil className="size-3.5" />Manage / add dive site</Link></article>
      <article className="rounded-2xl bg-surface p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-extrabold text-navy">Upcoming schedule</h3><span className="rounded-full bg-card px-2.5 py-1 text-xs font-bold text-primary">{diving.upcomingDays.length}</span></div><div className="mt-4 space-y-2">{diving.upcomingDays.slice(0, 4).map((item) => <div key={item.id} className="rounded-xl bg-card px-3 py-2"><p className="text-sm font-bold text-navy">{item.date}</p><p className="mt-0.5 text-xs text-muted-foreground">{item.status.replace("-", " ")} · {item.spaces_available ?? "—"} spaces · {item.is_active ? "Published" : "Hidden"}</p></div>)}{!diving.upcomingDays.length ? <p className="text-sm text-muted-foreground">No upcoming days yet.</p> : null}</div><Link href="/admin/dive-planner" className="mt-4 inline-flex items-center gap-1.5 text-xs font-extrabold text-primary hover:text-coral"><Pencil className="size-3.5" />Manage / add day</Link></article>
    </div></section>

    <section className="mt-10 rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-extrabold text-navy">Quick website tools</h2><p className="mt-1 text-sm text-muted-foreground">For common content that appears throughout the website.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/experience-categories" className="inline-flex items-center gap-2 rounded-xl bg-surface px-3 py-2.5 text-xs font-extrabold text-navy hover:text-primary"><Tag className="size-3.5" />Categories</Link><Link href="/admin/dive-sites" className="inline-flex items-center gap-2 rounded-xl bg-surface px-3 py-2.5 text-xs font-extrabold text-navy hover:text-primary"><MapPinned className="size-3.5" />Dive sites</Link><Link href="/admin/settings" className="inline-flex items-center gap-2 rounded-xl bg-surface px-3 py-2.5 text-xs font-extrabold text-navy hover:text-primary"><Settings className="size-3.5" />Site settings</Link></div></div></section>

    {active ? <section id="content-editor" className="mt-8 rounded-3xl border border-primary/20 bg-card p-6 shadow-lg sm:p-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Editing public page</p><h2 className="mt-1 text-xl font-extrabold text-navy">{active.name}</h2><p className="mt-1 text-sm text-muted-foreground">Leave a field blank to use the website default. Uploading an image replaces the existing page image.</p></div><Link href={active.href} target="_blank" className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-coral"><ExternalLink className="size-4" />Preview page</Link></div><form className="mt-7 grid gap-5" onSubmit={(event) => { event.preventDefault(); form.put("/admin/content", { forceFormData: true, preserveScroll: true, onSuccess: closeEditor }); }}><label className="text-sm font-bold text-navy">{active.titleLabel}<input value={form.data.title} onChange={(event) => form.setData("title", event.target.value)} placeholder={active.titleHint} className={field} /></label><label className="text-sm font-bold text-navy">{active.subtitleLabel}<textarea value={form.data.subtitle} onChange={(event) => form.setData("subtitle", event.target.value)} placeholder={active.subtitleHint} className={`${field} min-h-24 resize-y`} /></label><label className="text-sm font-bold text-navy">{active.bodyLabel}<textarea value={form.data.body} onChange={(event) => form.setData("body", event.target.value)} placeholder={active.bodyHint} className={`${field} min-h-32 resize-y`} /></label>{active.hasImage ? <label className="text-sm font-bold text-navy">Page image <span className="font-normal text-muted-foreground">(JPG, PNG or WEBP · max 5 MB)</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => form.setData("image", event.target.files?.[0] ?? null)} className={field} /></label> : null}<div className="flex flex-wrap gap-3"><button disabled={form.processing} className="rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground disabled:opacity-60">{form.processing ? "Saving…" : "Save changes"}</button><button type="button" onClick={closeEditor} className="rounded-full border border-border px-6 py-3 text-sm font-bold text-navy">Cancel</button></div></form></section> : null}
  </AdminLayout>;
}
