import { router, useForm, usePage } from "@inertiajs/react";
import { Pencil, Trash2, UsersRound } from "lucide-react";
import { useState } from "react";
import { AdminLayout } from "@/components/AdminLayout";
import { AdminAddPanel } from "@/components/AdminAddPanel";
type Member={id:number;name:string;role:string;bio?:string|null;languages?:string|null;qualifications?:string|null;image_path?:string|null;sort_order:number;is_active:boolean}; type Data={name:string;role:string;bio:string;languages:string;qualifications:string;image:File|null;sort_order:string;is_active:boolean};
const field="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"; const blank:Data={name:"",role:"",bio:"",languages:"",qualifications:"",image:null,sort_order:"0",is_active:true};
function Fields({form, required}:{form:ReturnType<typeof useForm<Data>>;required?:boolean}){return <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold text-navy">Full name<input required value={form.data.name} onChange={e=>form.setData("name",e.target.value)} className={field}/></label><label className="text-sm font-bold text-navy">Role<input required placeholder="e.g. Dive Instructor" value={form.data.role} onChange={e=>form.setData("role",e.target.value)} className={field}/></label><label className="text-sm font-bold text-navy">Photo<input required={required} type="file" accept="image/*" onChange={e=>form.setData("image",e.target.files?.[0]??null)} className={field}/></label><label className="text-sm font-bold text-navy">Display order<input type="number" min="0" value={form.data.sort_order} onChange={e=>form.setData("sort_order",e.target.value)} className={field}/></label><label className="text-sm font-bold text-navy md:col-span-2">Short bio<textarea value={form.data.bio} onChange={e=>form.setData("bio",e.target.value)} className={`${field} min-h-24`}/></label><label className="text-sm font-bold text-navy">Languages<input placeholder="e.g. English, Swahili, Italian" value={form.data.languages} onChange={e=>form.setData("languages",e.target.value)} className={field}/></label><label className="text-sm font-bold text-navy">Verified qualifications<input placeholder="Only use confirmed qualifications" value={form.data.qualifications} onChange={e=>form.setData("qualifications",e.target.value)} className={field}/></label></div>}
function Editor({item}:{item:Member}){const [open,setOpen]=useState(false);const form=useForm<Data>({name:item.name,role:item.role,bio:item.bio??"",languages:item.languages??"",qualifications:item.qualifications??"",image:null,sort_order:String(item.sort_order),is_active:item.is_active});if(!open)return <article className="flex items-center justify-between gap-4 rounded-2xl bg-card p-5 shadow-sm"><div className="flex min-w-0 items-center gap-4">{item.image_path?<img src={`/storage/${item.image_path}`} className="size-14 rounded-xl object-cover" alt=""/>:null}<div><b className="text-navy">{item.name}</b><p className="text-sm text-muted-foreground">{item.role} · {item.is_active?"Published":"Hidden"}</p></div></div><div className="flex gap-1"><button onClick={()=>setOpen(true)} className="rounded-full p-2 text-primary"><Pencil className="size-4"/></button><button onClick={()=>window.confirm(`Delete ${item.name}?`)&&router.delete(`/admin/team/${item.id}`)} className="rounded-full p-2 text-destructive"><Trash2 className="size-4"/></button></div></article>;return <article className="rounded-3xl border border-primary/30 bg-card p-6"><h3 className="font-extrabold text-navy">Edit {item.name}</h3><form className="mt-5" onSubmit={e=>{e.preventDefault();form.put(`/admin/team/${item.id}`,{onSuccess:()=>setOpen(false)})}}><Fields form={form}/><label className="mt-5 inline-flex gap-2 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_active} onChange={e=>form.setData("is_active",e.target.checked)}/>Publish profile</label><div className="mt-5 flex gap-3"><button className="rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Save changes</button><button type="button" onClick={()=>setOpen(false)} className="rounded-full border border-border px-5 py-3 text-sm font-bold text-navy">Cancel</button></div></form></article>}
export default function Team(){const {items}=usePage<{items:Member[]}>().props;const form=useForm<Data>(blank);return <AdminLayout title="Team & Standards"><AdminAddPanel title="Add team member" description="Use genuine names, roles and verified qualifications only."><form onSubmit={e=>{e.preventDefault();form.post("/admin/team",{onSuccess:()=>form.reset()})}}><Fields form={form} required/><label className="mt-5 inline-flex gap-2 text-sm font-bold text-navy"><input type="checkbox" checked={form.data.is_active} onChange={e=>form.setData("is_active",e.target.checked)}/>Publish now</label><button className="mt-5 block rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground">Add team member</button></form></AdminAddPanel><section className="mt-8 space-y-4"><h2 className="text-xl font-extrabold text-navy">Manage team</h2>{items.map(item=><Editor key={item.id} item={item}/>)}</section></AdminLayout>}
