import { router, useForm, usePage } from "@inertiajs/react";
import { KeyRound, Pencil, ShieldCheck, Trash2, UserRoundPlus } from "lucide-react";
import { useState } from "react";
import { AdminAddPanel } from "@/components/AdminAddPanel";
import { AdminLayout } from "@/components/AdminLayout";

type Account = { id: number; name: string; email: string; role: "admin" | "staff"; created_at: string };
type Data = { name: string; email: string; role: "admin" | "staff"; password: string; password_confirmation: string };
const inputClass = "mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20";
const blank: Data = { name: "", email: "", role: "staff", password: "", password_confirmation: "" };

function Fields({ form, required = false }: { form: ReturnType<typeof useForm<Data>>; required?: boolean }) {
  return <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold text-navy">Full name<input required value={form.data.name} onChange={(event) => form.setData("name", event.target.value)} className={inputClass} /></label><label className="text-sm font-bold text-navy">Email address<input required type="email" value={form.data.email} onChange={(event) => form.setData("email", event.target.value)} className={inputClass} /></label><label className="text-sm font-bold text-navy">Role<select value={form.data.role} onChange={(event) => form.setData("role", event.target.value as Data["role"])} className={inputClass}><option value="staff">Staff — manage bookings and website content</option><option value="admin">Admin — full access, including users</option></select></label><div className="hidden md:block" /><label className="text-sm font-bold text-navy">{required ? "Temporary password" : "New password (leave blank to keep current)"}<input required={required} type="password" autoComplete="new-password" value={form.data.password} onChange={(event) => form.setData("password", event.target.value)} className={inputClass} /></label><label className="text-sm font-bold text-navy">Confirm password<input required={required || Boolean(form.data.password)} type="password" autoComplete="new-password" value={form.data.password_confirmation} onChange={(event) => form.setData("password_confirmation", event.target.value)} className={inputClass} /></label></div>;
}

function AccountEditor({ item, currentId }: { item: Account; currentId?: number }) {
  const [open, setOpen] = useState(false);
  const form = useForm<Data>({ name: item.name, email: item.email, role: item.role, password: "", password_confirmation: "" });
  if (!open) return <article className="flex flex-col gap-4 rounded-2xl bg-card p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><ShieldCheck className="size-5" /></span><div className="min-w-0"><b className="block truncate text-navy">{item.name}{item.id === currentId ? " (You)" : ""}</b><p className="truncate text-sm text-muted-foreground">{item.email}</p><p className={`mt-1 text-xs font-bold ${item.role === "admin" ? "text-primary" : "text-emerald-600"}`}>{item.role === "admin" ? "Administrator" : "Staff"}</p></div></div><div className="flex shrink-0 gap-2"><button type="button" onClick={() => setOpen(true)} className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><Pencil className="size-3.5" />Edit</button>{item.id !== currentId ? <button type="button" onClick={() => window.confirm(`Delete ${item.name}'s account?`) && router.delete(`/admin/users/${item.id}`)} className="rounded-full p-2 text-destructive hover:bg-destructive/10" aria-label={`Delete ${item.name}`}><Trash2 className="size-4" /></button> : null}</div></article>;
  return <article className="rounded-3xl border border-primary/30 bg-card p-6"><h3 className="font-extrabold text-navy">Edit {item.name}</h3><p className="mt-1 text-sm text-muted-foreground">Use a new password only when you want to reset this account.</p><form className="mt-5" onSubmit={(event) => { event.preventDefault(); form.put(`/admin/users/${item.id}`, { onSuccess: () => setOpen(false) }); }}><Fields form={form} /><div className="mt-5 flex gap-3"><button className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground"><KeyRound className="size-4" />Save account</button><button type="button" onClick={() => setOpen(false)} className="rounded-full border border-border px-5 py-3 text-sm font-bold text-navy">Cancel</button></div></form></article>;
}

export default function Users() {
  const page = usePage<{ items?: Account[]; auth?: { user?: { id?: number } } }>().props;
  const items = Array.isArray(page.items) ? page.items.filter((item): item is Account => Boolean(item && item.name)) : [];
  const auth = page.auth;
  const form = useForm<Data>(blank);
  return <AdminLayout title="Users & Roles"><div className="mb-7 rounded-3xl bg-navy p-6 text-navy-foreground"><p className="text-xs font-bold uppercase tracking-[0.16em] text-turquoise">Access control</p><h2 className="mt-2 text-xl font-extrabold">Keep admin access simple and secure.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-navy-foreground/75">Administrators manage accounts and settings. Staff can manage bookings and public website content, but cannot access this page.</p></div><AdminAddPanel title="Add a staff member" description="Create an account and share the temporary password privately."><form onSubmit={(event) => { event.preventDefault(); form.post("/admin/users", { onSuccess: () => form.reset() }); }}><Fields form={form} required /><button className="mt-5 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-bold text-primary-foreground"><UserRoundPlus className="size-4" />Create account</button></form></AdminAddPanel><section className="mt-8 space-y-4"><div><h2 className="text-xl font-extrabold text-navy">Manage accounts</h2><p className="mt-1 text-sm text-muted-foreground">There must always be at least one administrator.</p></div>{items.map((item) => <AccountEditor key={item.id} item={item} currentId={auth?.user?.id} />)}</section></AdminLayout>;
}
